
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_manager_api_development
  username: postgres
  password: 456321
  
test:
  <<: *default
  database: portfolio_manager_api_test
  username: postgres
  password: 456321

production:
  <<: *default
  database: portfolio_manager_api_production
  username: portfolio_manager_api
  password: <%= ENV['PORTFOLIO_MANAGER_API_DATABASE_PASSWORD'] %>
